### ISSUE TITLE
read instances

### ISSUE THREAD

**Issue by hzzzzjzyq** [rohitkannan/DD-SAA#1]
thanks for your good work. i want to konw how can i get a Script to read instances

**Comment by rohitkannan** [comment]
Hi @hzzzzjzyq, thanks for your interest! I've just uploaded script files for running similar instances on HTCondor in a related repository here: https://github.com/rohitkannan/ER-DRO. You should be able to easily adapt those script files for the case studies here - I plan on adding similar script files to this repository in the next few months. Please let me know if you have any questions and if this resolved your issue @hzzzzjzyq.

**Comment by rohitkannan** [comment]
@hzzzzjzyq I've updated the data files and added scripts for running them on HTCondor. I've also included Python scripts for plotting the results. Please let me know if you have any questions.
